name: Test ZenCfg

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install package
      run: |
        python -m pip install -e .[all]
    - name: Test with pytest
      run: |
        pytest -vvv src/zencfg
